### ISSUE TITLE
Enhancement request for find() to place the cursor at the the first record that has a greater key satisfies the search when the exact key is not found, like CICS API STARTBR

### ISSUE THREAD

**Issue by liuskhk1** [ibmruntimes/vsam.js#14]
From the doc:
https://github.com/ibmruntimes/vsam.js#finding-a-record-in-a-vsam-dataset

- The find operation will place the cursor at the queried record (if found).
- The record object in the callback will by null if the query failed to retrieve a record.

So, it looks like the FIND method can be used to position the initial cursor, but it has to be an exact match. Otherwise, null will be returned and the cursor is not positioned which has a greater key satisfies the search.

It is requested to enhance the find() like CICS API 'STARTBR' with GTEQ option:
https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.4.0/reference/commands-api/dfhp4_startbr.html

<Quote>	
GTEQ :- specifies that, if the search for a record that has the same key (complete or generic) as that specified in the RIDFLD option is unsuccessful, the first record that has a greater key satisfies the search.
</Quote>

Please review and consider to implement this enhancement request.
Thanks & Regards,
Kelvin

**Comment by IgorTodorovskiIBM** [comment]
Hi, we could potentially do this with an extra parameter to Find. 
 
Currently it defaults to __KEY_EQ in the call to flocate (https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxbd00/flocate.htm).  See source here: https://github.com/ibmruntimes/vsam.js/blob/master/VsamFile.cpp, but we can provide a parameter to allow the user to override it and specify __KEY_GE.
 
Would this proposal satisfy the feature request?

**Comment by liuskhk1** [comment]
Yes, the proposed solution to provide parameter _KEY_GE should be fine.  Thanks a lot.

**Comment by gabylb** [comment]
This has been implemented in v3.0.0 with `findge()` and `findgeSync()`; please see https://github.com/ibmruntimes/vsam.js#find-a-record-in-a-vsam-dataset and https://github.com/ibmruntimes/vsam.js#synchronously-find-create-read-update-and-delete-functions.

I'll close the issue; please open a new one if you encounter an issue.
