### ISSUE TITLE
The write operation could not overwrite existing record with the same key

### ISSUE THREAD

**Issue by tangthth** [ibmruntimes/vsam.js#3]
### **Issue Description:**
The Readme says "The write operation will overwrite any existing record with the same key".  But actually it will not overwrite but fails with error message "TypeError: Failed to write".  Is it just a document issue?

### **Reproduce Steps:**
1. write a nodejs script like below to write a new record to a VSAM dataset
2. execute the script twice
<=== The 1st execution runs successfully.  The 2nd execution fails.

### **Logs:**
TypeError: Failed to write

### **Reference:**
    var newrecord={"key": "00001", "name": "USERNAMEA1", "gender": "FEMALE0001"}
    vsamObj.write(newrecord, function(err) {
        if (err !=null)	{
			console.log("Error in writing the new Record.")
			console.error("The Error is: " + err)
		}	
        console.log("Writing new record done.")
    })

**Comment by gabylb** [comment]
This was a documentation error and has been corrected as of the current latest v3.0.1. Please see  https://github.com/ibmruntimes/vsam.js#write-a-record-to-a-vsam-dataset:

_The write operation fails if a record with the same key already exists in the dataset. In vsam.js prior to v3.0.0, this behaviour was wrongly documented as "write() will overwrite any existing record with the same key"._
