### ISSUE TITLE
vsamObj.close() callback not get called if no error, inconsistent with delete() or dealloc()

### ISSUE THREAD

**Issue by tangthth** [ibmruntimes/vsam.js#4]
### **Issue Description:**
For vsamObj.close() API, the callback does not get called if there is no error closing the data set.  But for vsamObj.delete() or vsamObj.dealloc(), the callback does get called even if there is no error deleting or deallocating the data set, which is inconsistent.

### **Reproduce Steps:**
1. write a nodejs script to close an open vsam data set, deallocate the vsam data set and print logs to console in each callback.
2. execute the script:
<=== The log "Deallocating the vsam dataset" is printed to the console but the log "Closing the vsam dataset." is not printed, which are inconsistent.  vsamObj.delete() behaves similarly as vsamObj.deallocate().

### **Logs:**
No any error info or log is reported.

### **Reference:**
```
vsamObj.close(function(err) { 
    console.log("Closing the vsam dataset.") 
	if (err != null) {
		console.log("Error in closing vsam dataset.")
		console.error("The error is: " + err)
	}
	
})

vsamObj.dealloc(function (err) {
	console.log("Deallocating the vsam dataset.")
	if (err != null) {
		console.log("Error in deallocating vsam dataset.")
		console.error("The error is: " + err)
	}
})
```

**Comment by gabylb** [comment]
There was a documentation error prior to v3.0.0 and has been corrected. I think the original authors intended to make close() consistent with openSync(), though I don't know why it didn't have the Sync suffix. Please see https://github.com/ibmruntimes/vsam.js#close-a-vsam-dataset:

_This function takes no argument. Prior to vsam.js v3.0.0, it was wrongly documented as taking a callback argument._
